#!/bin/bash

## Alvarez and Ning validation case from supplement to `Stable Vortex
## Particle Method Formulation for Meshless Large-Eddy Simulation'
## https://dx.doi.org/10.2514/1.J063045

BIN=../../tools

##sigma=0.0408
##alpha=0.7
## Alvarez and Ning settings for 60k particles
sigma=0.0816
alpha=0.5
## ring radius
radius=1.0
## core radius
core=0.2
## nu = \Gamma/Re = 1/7500
nu=1.3e-4
dt=0.0025
kernel=-G
nthreads=4
depth=5
order=14
## 5% of peak vorticity
gtol=0.01
tol=1e-6
## number of time steps between remeshes
substeps=8
## number of times to call solver
nsteps=100

mkdir -p Data

## generate initial particle distribution
${BIN}/rvpm-grid -f vortex_ring -p ${radius} -p ${core} \
          -s ${sigma} -a ${alpha} -g ${gtol} -t ${tol} > ring.dat
##alpha=0.8
##${BIN}/rvpm-grid -f vortex_ring -p ${radius} -p ${core} \
##      -s ${sigma} -a ${alpha} -g 1e-2 -t 1e-4 > ring.dat

cp ring.dat input.dat
## time step
##dt=0.00625
for (( i=1; i<=${nsteps} ; i++ )) do
    echo step: $i
    opts="-n ${substeps} -d ${dt} ${kernel} -v ${nu} -T ${nthreads} -D ${depth} -L ${order}"
    echo rvpm-solve ${opts}
    ${BIN}/rvpm-solve ${opts} < input.dat > Data/solution-${i}.dat
    ## remesh
    ##${BIN}/rvpm-grid -r Data/solution-${i}.dat -a ${alpha} -s ${sigma} \
##		   -g ${gtol} -t ${tol} > input.dat
    cp Data/solution-${i}.dat input.dat
done
