#!/bin/bash

BIN=../../tools

sigma=0.03
alpha=0.6
radius=0.9
core=0.1
dt=0.0025
kernel=-W
reg=1e-1
nthreads=4

## generate initial particle distribution
${BIN}/rvpm-grid -f vortex_ring -p ${radius} -p ${core} \
      -s ${sigma} -a ${alpha} -g 1e-6 -t 1e-9 > ring.dat

cp ring.dat input.dat
## time step
for (( i=1; i<=200 ; i++ )) do
    echo step: $i
    ${BIN}/rvpm-solve -n 10 -d ${dt} ${kernel} -r ${reg} \
	  -T ${nthreads} < input.dat > Data/solution-${i}.dat
    ## remesh
    ${BIN}/rvpm-grid -r Data/solution-${i}.dat -a ${alpha} -s ${sigma} \
	  > input.dat
done
