#!/bin/bash

BIN=../../tools

sigma=0.03
alpha=0.6
radius=0.9
core=0.1
dt=0.0025
kernel=-W
reg=1e-1
nthreads=4
gtol=1e-3
tol=1e-6

## generate initial particle distribution
${BIN}/rvpm-grid -f vortex_ring -p ${radius} -p ${core} \
          -s ${sigma} -a ${alpha} -g ${gtol} -t ${tol} > ring.dat
##alpha=0.8
##${BIN}/rvpm-grid -f vortex_ring -p ${radius} -p ${core} \
##      -s ${sigma} -a ${alpha} -g 1e-2 -t 1e-4 > ring.dat

cp ring.dat input.dat
## time step
dt=0.00625
for (( i=1; i<=1 ; i++ )) do
    echo step: $i
    ${BIN}/rvpm-solve -n 4 -d ${dt} ${kernel} -r ${reg} \
	  -T ${nthreads} < input.dat > Data/solution-${i}.dat
    ## remesh
    ${BIN}/rvpm-grid -r Data/solution-${i}.dat -a ${alpha} -s ${sigma} \
	   -g ${gtol} -t ${tol} > input.dat
done
