#!/bin/bash

opfile=$1

rm -f ${opfile}.c
sed -e s/RVPM_REAL/gdouble/g -e s/_FLOAT//g -e s/FLOATFMT/lg/g \
    -e s/FLOATEXP/1.16e/g \
    ${opfile}.c.in > ${opfile}.c
## so that I don't accidentally edit it in place of the .c.in file ...
chmod a-w ${opfile}.c

#sed -e s/RVPM_REAL/gfloat/g -e s/_PREC/_f/g -e s/FLOATFMT/g/g \
#    -e s/FLOATEXP/1.16e/g \
#    ${opfile}.c.in > ${opfile}-float.c
